
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AMOR LAB
email: amor@cshl.edu
description: >- # this means to ignore newlines until "baseurl:" Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  Working on the future of science!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
minima:
  date_format: "%b %-d, %Y"
  # social_links:
  #   twitter: amor_lab
  #   github: Amor-Lab
twitter_username: amor_lab
github_username: Amor-Lab

# social:
#     - title: twitter
#       url: http://twitter.com/amor_lab
#     - title: github
#       url: http://github.com/Amor-Lab

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-titles-from-headings

setup:
  - name: Home
    link: home
  - name: Research
    link: research
  - name: Publications
    link: publications
  - name: People
    link: people
  - name: Contact
    link: contact

header_pages:
  - _pages/02_research.md
  - _pages/03_publications.md
  - _pages/04_people.md
  - _pages/05_contact.md

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 

include: ["_pages"]
makrdown: kramdown
permalink: pretty

exclude: ["_drafts"]

sass:
  load_paths:
    - _sass
    - /Users/luzjubierrezapater/.gem/ruby/2.7.2/gems/bootstrap-4.3.1


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
